.TH "/home/mateusberardo/Documents/Novaweb/VirtualKeyboard/gtkmm-virtual-keyboard/keyboardentry.h" 3 "Tue Feb 4 2020" "Version 1.0.0-alpha" "Gtkmm Virtual Keyboard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mateusberardo/Documents/Novaweb/VirtualKeyboard/gtkmm-virtual-keyboard/keyboardentry.h
.SH SYNOPSIS
.br
.PP
\fC#include <gtkmm/entry\&.h>\fP
.br
\fC#include <glibmm/ustring\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKeyboardEntry\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Gtkmm Virtual Keyboard from the source code\&.
