.TH "KeyboardEntry" 3 "Tue Feb 4 2020" "Version 1.0.0-alpha" "Gtkmm Virtual Keyboard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyboardEntry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <keyboardentry\&.h>\fP
.PP
Inherits Entry\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyboardEntry\fP ()"
.br
.ti -1c
.RI "void \fBappend_text\fP (Glib::ustring)"
.br
.RI "append_text Adiciona o texto recebido ao final do texto atual do \fBKeyboardEntry\fP "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KeyboardEntry::KeyboardEntry ()"
Construtor Padrão 
.SH "Member Function Documentation"
.PP 
.SS "void KeyboardEntry::append_text (Glib::ustring text)"

.PP
append_text Adiciona o texto recebido ao final do texto atual do \fBKeyboardEntry\fP 
.PP
\fBParameters\fP
.RS 4
\fItext\fP Texto a ser adicionado 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Gtkmm Virtual Keyboard from the source code\&.
