.TH "/home/mateusberardo/Documents/Novaweb/VirtualKeyboard/gtkmm-virtual-keyboard/main.cpp" 3 "Tue Feb 4 2020" "Version 1.0.0-alpha" "Gtkmm Virtual Keyboard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/mateusberardo/Documents/Novaweb/VirtualKeyboard/gtkmm-virtual-keyboard/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <gtkmm/application\&.h>\fP
.br
\fC#include <gtkmm/window\&.h>\fP
.br
\fC#include <gtkmm/box\&.h>\fP
.br
\fC#include <gtkmm/entry\&.h>\fP
.br
\fC#include 'keyboardbutton\&.h'\fP
.br
\fC#include 'keyboard\&.h'\fP
.br
\fC#include 'keyboardentry\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Gtkmm Virtual Keyboard from the source code\&.
